name: Build Docker Image

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set Environment Variables
      run: |
        echo "::set-env name=GITHUB_SHA::${{ env.GITHUB_SHA }}"

    - name: Build Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: my-image-repository/my-image:${{ env.GITHUB_SHA }}
        
    - name: Set Environment Variable
      run: |
        echo "::set-env name=ACTIONS_ALLOW_UNSECURE_COMMANDS::true"

