

name: newPush

on:

  push:
    branches: [ "main" ]



jobs:

  build:

    runs-on: ubuntu-latest


    steps:

      - uses: actions/checkout@v3

      - run: pip install Flask

      - run: python main.py check_syntax
